# Generated by Django 3.1.4 on 2020-12-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='media/slider/%Y/%m'),
        ),
    ]
