# Generated by Django 3.1.4 on 2020-12-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20201228_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='channel_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='catagory',
            field=models.CharField(choices=[('code', 'code'), ('mobile_review', 'mobile_review'), ('vlogs', 'vlogs'), ('comedy', 'comedy'), ('gaming', 'gaming'), ('film_making', 'film_making'), ('cooking', 'cooking'), ('motivation', 'motivation')], max_length=255),
        ),
    ]
