# Generated by Django 3.1.4 on 2020-12-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20201228_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtuber',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='catagory',
            field=models.CharField(choices=[('code', 'code'), ('mobile_review', 'mobile_review'), ('vlogs', 'vlogs'), ('comedy', 'comedy'), ('gaming', 'gaming'), ('film_making', 'film_making'), ('cooking', 'cooking'), ('motivation', 'motivation'), ('music', 'music')], max_length=255),
        ),
    ]
